@extends('layouts.app')

@section('content')
    <div class="m-5">
        <h4> Terms of Use </h4>
        <p> These Terms of Use ("Terms") govern your use of the Facework website, located at www.facework.com.ng and services ("Site") provided by Facework, Inc. ("Facework"). Please read these Terms before using or continuing to use the Site. Do not agree to the Terms unless you both fully understand and accept each provision. By using or continuing to use the Site, you represent and warrant that you understand, agree to, and accept all terms and conditions contained in these Terms. </p><br>

        <p><b>1 . General terms</b> <br>
        The Facework Inc. provides this Site to users (“Clients”) seeking business promotions and interactions to other users who accept these Terms. It is a platform to showcase the business ventures of business owners and entrepreneurs. The term "you" or "You" or “User” or “Users” shall refer to Clients, any person or entity who views, uses, accesses, browses or submits any content or material to the Site. These Terms are entered into by and between Facework and you.
        To the extent that anything in or associated with the Site is in conflict or inconsistent with these Terms, the Terms shall control. Any express waiver or failure to exercise promptly any right under the Terms will not create a continuing waiver or any expectation of non-enforcement. If any provision of the Terms is held invalid by any law or regulation of any government, or by any court or arbitrator, the parties agree that such provision will be replaced with a new provision that accomplishes the original business purpose, and the other provisions of the Terms will remain in full force and effect. </p> <br>
        <p><b>2. Services</b> <br>
        This site provides a platform designed to help business ventures of any kind (Professional/Vocational) improve productivity and efficiency in the Nigerian market share. It's a platform to help business men and women interact with potential clients who are interested in the different services they offer.
        It is a platform committed to solving a common problem of visibility faced by several businesses in Nigeria. It is also an avenue to help many young Nigerians create new profitable startups and acquire skills that can generate income and productivity for themselves. </p> <br>
        <p><b>3. Data Protection and Privacy Policy </b> <br>
        Facework shall implement and maintain reasonable procedures for protecting personal information in compliance with applicable law and the Facework Privacy Policy.</p> <br>
        <p><b>4. Disclaimers and Limitation of Liability </b> <br>
        DISCLAIMERS: USE OF THE SITE IS AT YOUR SOLE RISK UNLESS OTHERWISE EXPLICITLY STATED. THE SITE, INCLUDING THE INFORMATION, SERVICES, AND CONTENT, IS PROVIDED ON AN "AS IS", "AS AVAILABLE", AND "WITH ALL FAULTS" BASIS. FACEWORK DISCLAIMS ALL EXPRESS OR IMPLIED CONDITIONS, REPRESENTATIONS, AND WARRANTIES OF ANY KIND, INCLUDING ANY IMPLIED WARRANTY OR CONDITION OF MERCHANTABILITY, SATISFACTORY QUALITY, OR FITNESS FOR A PARTICULAR PURPOSE. FACEWORK MAKES NO REPRESENTATIONS, WARRANTIES, CONDITIONS OR GUARANTEES AS TO THE USEFULNESS, QUALITY, SUITABILITY, TRUTH, ACCURACY, OR COMPLETENESS OF THE SITE. <br>
        FACEWORK MAKES NO WARRANTY OR REPRESENTATIONS THAT: (A) THE SITE WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE; (B) THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE WEBSITE WILL BE ACCURATE OR RELIABLE; (C) THE QUALITY OF ANY PRODUCTS, SERVICES, CONTENT, INFORMATION, OR OTHER MATERIAL PURCHASED OR OBTAINED FROM TUTORS WILL MEET YOUR EXPECTATIONS OR REQUIREMENTS; OR (D) ANY ERRORS IN THE SITE WILL BE CORRECTED.
        YOU ASSUME ALL RISK FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM OBTAINING ANY CONTENT FROM THE SITE, INCLUDING ANY DAMAGES RESULTING FROM COMPUTER VIRUSES. <br>
        LIMITATION OF LIABILITY: TO THE FULLEST EXTENT PERMISSIBLE BY APPLICABLE LAW, IN NO EVENT SHALL “FACEWORK” OR ITS FUTURE PARENT OR AFFILIATED COMPANIES, BE LIABLE TO YOU FOR ANY PERSONAL INJURY, PROPERTY DAMAGE, LOST PROFITS, COST OF SUBSTITUTE GOODS OR SERVICES, LOSS OF DATA, LOSS OF GOODWILL, WORK STOPPAGE, COMPUTER AND/OR DEVICE OR TECHNOLOGY FAILURE OR MALFUNCTION OR FOR ANY FORM OF DIRECT OR INDIREC, SPECIAL, INCIDENTAL, CONSEQUENTIAL, EXEMPLARY OR PUNITIVE DAMAGES BASED ON ANY CAUSES OF ACTION ARISING OUT OF USE OF THE WEBSITE OR ANY ALLEGED FAILURE OF PERFORMANCE, ERROR, OMISSION, INTERUPTION, DELETION, DEFECT, OR DELAY IN SERVICE, OPERATION, OR TRANSMISSION OF THE WEBSITE, OR ANY ALLEGED COMPUTER VIRUS, COMMUNICATION LINE FAILURE, THEFT OR DESTRUCTION OF PROPERTY, AND/OR UNAUTHORISED ACCESS TO, ALTERATION OF, OR USE OF OR POSTING OF ANY RECORD, CONTENT OR TECHNOLOGY, PERTAINING TO OR ON THE WEBSITE. YOU AGREE THAT THIS LIMITATION OF LIABILITY APPLIES WHETHER SUCH ALLEGATIONS ARE FOR THE BREACH OF CONTRACT, TORTOUS BEHAVIOR, NEGLIGENCE, OR FALL UNDER ANY OTHER CAUSE OF ACTION, REGARDLESS OF THE BASIS UPON WHICH LIABILITY IS CLAIMED AND EVEN IF “FACEWORK” OR FUTURE PARENT OR AFFILIATED COMPANIES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH LOSS OF DAMAGE WITHOUT LIMITING THE GENERALITY OF THE FOREGOING, YOU ALSO SPECIFICALLY ACKNOLWEDGE THAT “FACEWORK” OR FUTURE PARENT OR AFFLIATED COMPANIES ARE NOT LIABLE FOR ANY ACTUAL OR ALLEGED DEFAMATORY, OFFENSIVE OR ILLEGAL CONDUCT OF OTHER USERS OF THE WEBSITE OR ANY OTHER TIRD PARTIES.
        IF APPLICABLE LAW DOES NOT ALLOW ALL OR ANY PART OF THE ABOVE LIMITATION OF LIABIBILTY TO YOU. THE LIMITATIONS WILL APPLY TO YOU ONLY TO THE EXTENT PERMITTED BY APPLICABLE LAW.</p> <br>
        <p><b>5. Intellectual property rights </b> <br>
        Facework grants you permission (which may be revoked at any time for any reason or no reason) to use the Site for the services as provided herein and in accordance with these Terms of Use and solely for your own personal, non-commercial use (except as provided herein), provided you do not remove any trademark, copyright or other notice contained on such pages. No other use is permitted. You may not, for example, incorporate the information, content, or other material in any database, compilation, archive or cache. Except as specifically authorized by Facework, you may not deep-link to the Site for any purpose or access the Site manually or with any robot, spider, web crawler, extraction software, automated process or device to scrape, copy, or monitor any portion of the Site or any information, content, or material on the Site. Facework reserves all of its statutory and common law rights against any person or entity who violates this paragraph. You may not link or frame to any pages of the Site or any content contained therein, whether in whole or in part, without prior written consent from Facework. You may like or follow Facework or share links to the Site via social networking technology referenced on the Site. Any rights not expressly granted herein are reserved.
        Except as expressly authorized by Facework or by Content providers, you agree not to reproduce, modify, rent, lease, loan, sell, distribute, mirror, frame, republish, download, transmit, or create derivative works of the Content of others, in whole or in part, by any means. You must not modify, decompile, or reverse engineer any software Facework discloses to you, and you must not remove or modify any copyright or trademark notice, or other notice of ownership.
        "Facework Trademarks" means all names, marks, brands, logos, designs, trade dress, slogans and other designations Facework uses in connection with its products and services. You may not remove or alter any Facework Trademarks, or co-brand your own products or material with Facework Trademarks, without Facework's prior written consent. You acknowledge Facework's rights in Facework Trademarks and agree that any use of Facework Trademarks by you shall inure to Facework's sole benefit. You agree not to incorporate any Facework Trademarks into your trademarks, service marks, company names, internet addresses, domain names, or any other similar designations, for use on or in connection with computer or internet-related products, services or technologies.
        Unless explicitly stated herein, nothing in these Terms shall be construed as conferring any license to intellectual property rights, whether by estoppels, implication, or otherwise. Permission is granted to display, copy, distribute and download Content owned by Facework on this Site provided that: (a) the copyright notice pertaining to the Content remains, and a permission notice (e.g., "used with permission") is added to such Content; (b) the use of such Content is solely for personal and non-commercial use; (c) such Content will not be copied or posted on any networked computer or published in any medium, except as explicitly permitted by valid permission or license covering such materials; and (d) no modifications are made to such Content. This permission terminates automatically without notice if you breach any of the terms or conditions in this document. Upon termination, you must immediately destroy any downloaded and/or printed Content. </p> <br>
        <p><b>6. Advertisements and promotions  </b> <br>
        Facework may run advertisements and promotions from third parties on the Site. Your correspondence or business dealings with, or participation in promotions of, advertisers other than Facework found on or through the Site, including payment and delivery of related goods or services, and any other terms, conditions, warranties or representations associated with such dealings, are solely between you and such advertiser. Facework is not responsible or liable for any loss or damage of any sort incurred as the result of any such dealings or as the result of the presence of such non-Facework advertisers on the Site.  </p> <br>
        <p><b>7. Notices; modification and termination of services; amendment of terms   </b> <br>
        Facework may provide notice to Users via email, regular mail, or posting notices or links to notices on the Site. Facework reserves the right at any time to modify, suspend or terminate the services (or any part thereof), and/or use of or access to them, with or without notice. Facework may also delete, or bar access to or use of, all related information and files. Facework will not be liable to Users or any third-party for any modification, suspension, or termination of service, or loss of related information. Facework may amend these Terms at any time by posting the amended terms on this Site.  </p> <br>
        <p><b>8. Contact Information  </b> <br>
        All questions, comments and enquiries should be directed 
        By email to <a href="mailto:contact.facework@gmail.com">contact.facework@gmail.com</a> , and/or by post to its registered office.
        We will to speedily respond to any queries or complaints as soon as we get it.  </p> <br>
        
    </div>

@endsection




